# my_snowflake_project:
#   target: dev
#   outputs:
#     dev:
#       type: snowflake
#       account: 'not needed'
#       user: 'not needed'
#       role: accountadmin
#       database: OMNI_MANAGEMENT  # Updated to the DB you were using earlier
#       schema: dev                # Ensure this schema exists in Snowflake!
#       warehouse: COMPUTE_WH      # Updated to your likely warehouse
#     prod:
#       type: snowflake
#       account: 'not needed'
#       user: 'not needed'
#       role: accountadmin
#       database: OMNI_MANAGEMENT
#       schema: prod
#       warehouse: COMPUTE_WH

my_snowflake_project:
  outputs:
    dev:
      account: 'not needed'
      database: OMNI_MANAGEMENT
      password: Shekhimran@7538
      role: SYSADMIN
      schema: RAW
      threads: 1
      type: snowflake
      user: 'not needed'
      warehouse: COMPUTE_WH
  target: dev