my_snowflake_project:
  outputs:
    dev:
      account: 'not needed'
      database: OMNI_MANAGEMENT
      password: 'not needed'
      role: SYSADMIN
      schema: DEV
      threads: 1
      type: snowflake
      user: 'not needed'
      warehouse: COMPUTE_WH
  target: dev